# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - rosdep install --from-paths src --ignore-src -r -y
      - colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Debug --parallel-workers 10